apiVersion: v1
kind: Pod
spec:
  shareProcessNamespace: true
  containers:
    - name: sa-spark-driver-wordcount
      env:
        - name: NAME
          value: "Vijay-sa-spark-driver-wordcount"
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
      livenessProbe:
        exec:
          command:
            - /bin/sh
            - -c
            - echo healthy at $(date) > /health-check/healthy
      volumeMounts:
        - name: health-check
          mountPath: /health-check
    - name: pods-vjbox-container
      livenessProbe:
        exec:
          command:
            - sh
            - -c
            - |-
              MOUNT_PATH="/health-check"
              FILE_TO_WATCH="$MOUNT_PATH/healthy"
              LAST_HEARTBEAT=$(stat -c %Y $FILE_TO_WATCH)
              ELAPSED_TIME_SINCE_AFTER_HEARTBEAT=$(expr $(date +%s) - $LAST_HEARTBEAT)
              HEARTBEAT_TIMEOUT_THRESHOLD=30
              echo healthy at date=$(date) - LAST_HEARTBEAT=$LAST_HEARTBEAT - ELAPSED_TIME_SINCE_AFTER_HEARTBEAT=$ELAPSED_TIME_SINCE_AFTER_HEARTBEAT >> /health-check/terminated.txt
              if [ "$ELAPSED_TIME_SINCE_AFTER_HEARTBEAT" -gt "$HEARTBEAT_TIMEOUT_THRESHOLD" ]; then $HEALTHY=0; fi
        initialDelaySeconds: 20
        periodSeconds: 10
      env:
        - name: HEALTHY
          value: 1
        - name: NAME
          value: "Vijay-pods-vjbox-container"
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
      image: vdonthireddy/vjbox:4.0
      args:
        - /bin/sh
        - -c
        - |-
          while :; 
          do 
            if [ $HEALTHY -eq 0 ]; then
              break
            fi
            echo "healthcheck" > /health-check/pods-vjbox-container.txt; 
            sleep 10; 
          done
      volumeMounts:
        - name: health-check
          mountPath: /health-check
  #    - name: observerbox
  #      env:
  #        - name: NAME
  #          value: "Vijay-observerbox"
  #        - name: POD_UID
  #          valueFrom:
  #            fieldRef:
  #              fieldPath: metadata.uid
  #      image: vdonthireddy/observerbox:centos
  #      args:
  #        - /bin/bash
  #        - ./terminate.sh
  #      volumeMounts:
  #        - name: health-check
  #          mountPath: /health-check
  volumes:
    - name: health-check
      emptyDir: { }