apiVersion: v1
kind: Pod
spec:
  shareProcessNamespace: true
  containers:
    - name: sa-spark-driver-wordcount
      livenessProbe:
        exec:
          command:
            - /bin/sh
            - -c
            - echo healthy at $(date) > /logging-volume/healthy
      volumeMounts:
        - name: logging-volume
          mountPath: /logging-volume
    - name: pods-vjbox-container
      image: vdonthireddy/vjbox:2.0
      args:
        - /bin/sh
        - -c
        - while :; do echo "healthcheck" > /logging-volume/pods-vjbox-container.txt; sleep 10 ; done
      volumeMounts:
        - name: logging-volume
          mountPath: /logging-volume
    - name: observerbox
      image: vdonthireddy/observerbox:1.0
      args:
        - /bin/bash
        - ./terminate.sh
      volumeMounts:
        - name: logging-volume
          mountPath: /logging-volume
  volumes:
    - name: logging-volume
      emptyDir: {}

#      - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600

#      args:
#        - /bin/sh
#        - -c
#        - touch /logging-volume/healthy; sleep 30
#      livenessProbe:
#        exec:
#          command:
#            - cat
#            - /logging-volume/healthy
#        initialDelaySeconds: 5
#        periodSeconds: 5