apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-creator
  namespace: spark-on-k8s
rules:
  - apiGroups:
      - "" # "" indicates the core API group
    resources:
      - services
      - configmaps
      - pods
      - secrets
      - endpoints
      - persistentvolumeclaims
    verbs:
      - get
      - watch
      - list
      - create
      - update
      - patch
      - delete